use crate::types::{
    Animation, Audio, CallbackQuery, Chat, ChatMember, ChatPermissions, ChatPhoto, Contact, Dice,
    Document, File, Game, GameHighScore, InlineQuery, Invoice, Location, Message, PassportData,
    Poll, PreCheckoutQuery, ShippingQuery, Sticker, StickerSet, Update, User, UserProfilePhotos,
    Venue, Video, VideoNote, Voice,
};
mod add_sticker_to_set;
mod answer_callback_query;
mod answer_inline_query;
mod answer_pre_checkout_query;
mod answer_shipping_query;
mod copy_message;
mod create_new_sticker_set;
mod delete_chat_photo;
mod delete_chat_sticker_set;
mod delete_message;
mod delete_sticker_from_set;
mod delete_webhook;
mod edit_message_caption;
mod edit_message_live_location;
mod edit_message_media;
mod edit_message_reply_markup;
mod edit_message_text;
mod export_chat_invite_link;
mod forward_message;
mod get_chat;
mod get_chat_administrators;
mod get_chat_member;
mod get_chat_members_count;
mod get_file;
mod get_game_high_scores;
mod get_sticker_set;
mod get_updates;
mod get_user_profile_photos;
mod kick_chat_member;
mod leave_chat;
mod pin_chat_message;
mod promote_chat_member;
mod restrict_chat_member;
mod send_animation;
mod send_audio;
mod send_chat_action;
mod send_contact;
mod send_dice;
mod send_document;
mod send_game;
mod send_invoice;
mod send_location;
mod send_media_group;
mod send_message;
mod send_photo;
mod send_poll;
mod send_sticker;
mod send_venue;
mod send_video;
mod send_video_note;
mod send_voice;
mod set_chat_administrator_custom_title;
mod set_chat_description;
mod set_chat_permissions;
mod set_chat_photo;
mod set_chat_sticker_set;
mod set_chat_title;
mod set_game_score;
mod set_my_commands;
mod set_passport_data_errors;
mod set_sticker_position_in_set;
mod set_sticker_set_thumb;
mod set_webhook;
mod stop_message_live_location;
mod stop_poll;
mod unban_chat_member;
mod unpin_all_chat_messages;
mod unpin_chat_message;
mod upload_sticker_file;

pub use add_sticker_to_set::AddStickerToSet;
pub use answer_callback_query::AnswerCallbackQuery;
pub use answer_inline_query::AnswerInlineQuery;
pub use answer_pre_checkout_query::AnswerPreCheckoutQuery;
pub use answer_shipping_query::AnswerShippingQuery;
pub use copy_message::CopyMessage;
pub use create_new_sticker_set::CreateNewStickerSet;
pub use delete_chat_photo::DeleteChatPhoto;
pub use delete_chat_sticker_set::DeleteChatStickerSet;
pub use delete_message::DeleteMessage;
pub use delete_sticker_from_set::DeleteStickerFromSet;
pub use delete_webhook::DeleteWebhook;
pub use edit_message_caption::EditMessageCaption;
pub use edit_message_live_location::EditMessageLiveLocation;
pub use edit_message_media::EditMessageMedia;
pub use edit_message_reply_markup::EditMessageReplyMarkup;
pub use edit_message_text::EditMessageText;
pub use export_chat_invite_link::ExportChatInviteLink;
pub use forward_message::ForwardMessage;
pub use get_chat::GetChat;
pub use get_chat_administrators::GetChatAdministrators;
pub use get_chat_member::GetChatMember;
pub use get_chat_members_count::GetChatMembersCount;
pub use get_file::GetFile;
pub use get_game_high_scores::GetGameHighScores;
pub use get_sticker_set::GetStickerSet;
pub use get_updates::GetUpdates;
pub use get_user_profile_photos::GetUserProfilePhotos;
pub use kick_chat_member::KickChatMember;
pub use leave_chat::LeaveChat;
pub use pin_chat_message::PinChatMessage;
pub use promote_chat_member::PromoteChatMember;
pub use restrict_chat_member::RestrictChatMember;
pub use send_animation::SendAnimation;
pub use send_audio::SendAudio;
pub use send_chat_action::SendChatAction;
pub use send_contact::SendContact;
pub use send_dice::SendDice;
pub use send_document::SendDocument;
pub use send_game::SendGame;
pub use send_invoice::SendInvoice;
pub use send_location::SendLocation;
pub use send_media_group::SendMediaGroup;
pub use send_message::SendMessage;
pub use send_photo::SendPhoto;
pub use send_poll::SendPoll;
pub use send_sticker::SendSticker;
pub use send_venue::SendVenue;
pub use send_video::SendVideo;
pub use send_video_note::SendVideoNote;
pub use send_voice::SendVoice;
pub use set_chat_administrator_custom_title::SetChatAdministratorCustomTitle;
pub use set_chat_description::SetChatDescription;
pub use set_chat_permissions::SetChatPermissions;
pub use set_chat_photo::SetChatPhoto;
pub use set_chat_sticker_set::SetChatStickerSet;
pub use set_chat_title::SetChatTitle;
pub use set_game_score::SetGameScore;
pub use set_my_commands::SetMyCommands;
pub use set_passport_data_errors::SetPassportDataErrors;
pub use set_sticker_position_in_set::SetStickerPositionInSet;
pub use set_sticker_set_thumb::SetStickerSetThumb;
pub use set_webhook::SetWebhook;
pub use stop_message_live_location::StopMessageLiveLocation;
pub use stop_poll::StopPoll;
pub use unban_chat_member::UnbanChatMember;
pub use unpin_all_chat_messages::UnpinAllChatMessages;
pub use unpin_chat_message::UnpinChatMessage;
pub use upload_sticker_file::UploadStickerFile;
