mod poll_answer;
mod vec<_string>;
mod bool;
mod chat_location;
mod inline_keyboard_markup;
mod i32;
mod string;
mod i32;
mod i32;
mod photo_size;
mod i32;
mod i32;
mod i32;
mod i32;
mod string;
mod i32;
mod i32;
mod vec<i32>;
mod i32;
mod i32;
mod string;
mod i32;
mod vec<_array> of _photo_size;
mod string;
mod bool;
mod keyboard_button_poll_type;
mod string;
mod bool;
mod vec<_array> of _inline_keyboard_button;
mod bool;
mod bool;
mod string;
mod bool;
mod string;
mod i32;
mod bool;
mod string;
mod string;
mod i32;
mod vec<_message_entity>;
mod bool;
mod i32;
mod string;
mod bool;
mod i32;
mod photo_size;
mod f64;
mod string;
mod i32;
mod input_message_content;
mod input_message_content;
mod input_message_content;
mod input_message_content;
mod input_message_content;
mod input_message_content;
mod i32;
mod i32;
mod i32;
mod i32;
mod inline_keyboard_markup;
mod input_message_content;
mod input_message_content;
mod input_message_content;
mod input_message_content;
mod input_message_content;
mod input_message_content;
mod input_message_content;
mod input_message_content;
mod bool;
mod i32;
mod string;
mod string;
mod string;
mod i32;
mod i32;
mod string;
mod shipping_address;
mod vec<_labeled_price>;
mod string;
mod shipping_address;
mod order_info;
mod encrypted_credentials;
mod i32;
mod string;
mod string;
mod string;
mod string;
mod string;
mod string;
mod string;
mod string;
mod string;
mod string;
mod string;
mod animation;
mod i32;


pub use poll_answer::PollAnswer;
pub use vec<_string>::Vec<String>;
pub use bool::Bool;
pub use chat_location::ChatLocation;
pub use inline_keyboard_markup::InlineKeyboardMarkup;
pub use i32::I32;
pub use string::String;
pub use i32::I32;
pub use i32::I32;
pub use photo_size::PhotoSize;
pub use i32::I32;
pub use i32::I32;
pub use i32::I32;
pub use i32::I32;
pub use string::String;
pub use i32::I32;
pub use i32::I32;
pub use vec<i32>::Vec<I32>;
pub use i32::I32;
pub use i32::I32;
pub use string::String;
pub use i32::I32;
pub use vec<_array> of _photo_size::Vec<Array> Of PhotoSize;
pub use string::String;
pub use bool::Bool;
pub use keyboard_button_poll_type::KeyboardButtonPollType;
pub use string::String;
pub use bool::Bool;
pub use vec<_array> of _inline_keyboard_button::Vec<Array> Of InlineKeyboardButton;
pub use bool::Bool;
pub use bool::Bool;
pub use string::String;
pub use bool::Bool;
pub use string::String;
pub use i32::I32;
pub use bool::Bool;
pub use string::String;
pub use string::String;
pub use i32::I32;
pub use vec<_message_entity>::Vec<MessageEntity>;
pub use bool::Bool;
pub use i32::I32;
pub use string::String;
pub use bool::Bool;
pub use i32::I32;
pub use photo_size::PhotoSize;
pub use f64::F64;
pub use string::String;
pub use i32::I32;
pub use input_message_content::InputMessageContent;
pub use input_message_content::InputMessageContent;
pub use input_message_content::InputMessageContent;
pub use input_message_content::InputMessageContent;
pub use input_message_content::InputMessageContent;
pub use input_message_content::InputMessageContent;
pub use i32::I32;
pub use i32::I32;
pub use i32::I32;
pub use i32::I32;
pub use inline_keyboard_markup::InlineKeyboardMarkup;
pub use input_message_content::InputMessageContent;
pub use input_message_content::InputMessageContent;
pub use input_message_content::InputMessageContent;
pub use input_message_content::InputMessageContent;
pub use input_message_content::InputMessageContent;
pub use input_message_content::InputMessageContent;
pub use input_message_content::InputMessageContent;
pub use input_message_content::InputMessageContent;
pub use bool::Bool;
pub use i32::I32;
pub use string::String;
pub use string::String;
pub use string::String;
pub use i32::I32;
pub use i32::I32;
pub use string::String;
pub use shipping_address::ShippingAddress;
pub use vec<_labeled_price>::Vec<LabeledPrice>;
pub use string::String;
pub use shipping_address::ShippingAddress;
pub use order_info::OrderInfo;
pub use encrypted_credentials::EncryptedCredentials;
pub use i32::I32;
pub use string::String;
pub use string::String;
pub use string::String;
pub use string::String;
pub use string::String;
pub use string::String;
pub use string::String;
pub use string::String;
pub use string::String;
pub use string::String;
pub use string::String;
pub use animation::Animation;
pub use i32::I32;
